# import = [
#     "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
# ]

## Vague color scheme
[colors.primary]
background = '#141415'
foreground = '#cdcdcd'

[colors.normal]
black = '#252530'
red = '#d8647e'
green = '#7fa563'
yellow = '#f3be7c'
blue = '#6e94b2'
magenta = '#bb9dbd'
cyan = '#aeaed1'
white = '#cdcdcd'

[colors.bright]
black = '#606079'
red = '#e08398'
green = '#99b782'
yellow = '#f5cb96'
blue = '#8ba9c1'
magenta = '#c9b1ca'
cyan = '#bebeda'
white = '#d7d7d7'

[window]
padding = { x = 3, y = 3 }

[font]
normal = { family = "FiraCode Nerd Font Mono" }
size = 15
